---
- hosts: vault
  gather_facts: yes

  vars_files:
    - vars.yaml

  tasks:
    - name: Add Hashicorp package repository
      become: yes
      deb822_repository:
        name: hashicorp
        types: [deb]
        architectures: [amd64]
        uris: "https://apt.releases.hashicorp.com"
        signed_by: "https://apt.releases.hashicorp.com/gpg"
        suites: [bookworm]
        components:
          - main
        state: present
        enabled: yes

    - name: Install Hashicorp Vault
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - vault

