---
- hosts: worker_nodes
  become: yes
  gather_facts: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Skip joining Worker node if already joined to the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: stat_result

    - meta: end_play
      when: stat_result.stat.exists

    - name: Create JoinConfiguration
      blockinfile:
        path: "/tmp/join-config.yaml"
        create: true
        block: |
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: JoinConfiguration
          nodeRegistration:
            kubeletExtraArgs:
              # address: "{{ ansible_default_ipv4.address }}"
              node-ip: "{{ internal_ip }}"
          discovery:
            bootstrapToken:
              token: "{{ lookup('file', '/tmp/join_token') }}"
              caCertHashes:
                - "{{ lookup('file', '/tmp/cert_hash') }}"
              apiServerEndpoint: "{{ lookup('file', '/tmp/api_server_endpoint') }}"

    - name: Join the Worker nodes to the cluster.
      command: "kubeadm join --config /tmp/join-config.yaml"

