---
- name: "Install HAProxy repositories and packages"
  hosts: haproxy
  gather_facts: true

  vars_files:
    - vars.yaml

  tasks:
    - name: Add HAProxy package repository
      become: true
      ansible.builtin.deb822_repository:
        name: haproxy
        types: [deb]
        architectures: [amd64]
        uris: "http://haproxy.debian.net"
        signed_by: "https://haproxy.debian.net/haproxy-archive-keyring.gpg"
        suites: [bookworm-backports-3.2]
        components:
          - main
        state: present
        enabled: true

    - name: Install HAProxy
      become: true
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - "haproxy=3.2.*"

    - name: Copy the config file to the remote machine
      become: true
      ansible.builtin.copy:
        src: "../../configs/haproxy.cfg"
        dest: "/etc/haproxy/haproxy.cfg"
        owner: haproxy
        group: haproxy
        mode: "0644"

    - name: Start and enable HA Proxy
      become: true
      ansible.builtin.service:
        name: haproxy
        state: "reloaded"
        enabled: true
