---
- name: "Copy cluster configuration to remote machine"
  hosts: operators
  gather_facts: true

  vars_files:
    - vars.yaml

  tasks:
    - name: Copy the config file to the remote machine
      become: true
      ansible.builtin.copy:
        src: "../../configs/cluster.hcl"
        dest: "/etc/openbao/openbao.hcl"
        owner: openbao
        group: openbao
        mode: "0644"

    - name: Start OpenBao
      become: true
      ansible.builtin.service:
        name: openbao
        state: "started"
        enabled: true
