---
- hosts: openbao
  gather_facts: yes

  vars_files:
    - vars.yaml

  tasks:
    - name: Install packages
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - qemu-guest-agent

    - name: Start QEMU Guest Agent
      become: yes
      ansible.builtin.service:
        name: qemu-guest-agent
        state: "started"
        enabled: true

    # Band-aid fix for systemd-networkd-wait-online hanging.
    - name: Create the directory for systemd-networkd-wait-online.service override
      become: yes
      ansible.builtin.file:
        path: /etc/systemd/system/systemd-networkd-wait-online.service.d/
        state: directory
        owner: root
        group: root
        mode: '0644'

    - name: Set the interface for systemd-networkd-wait-online.service
      become: yes
      ansible.builtin.copy:
        dest: /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --timeout=3 --any

