---
- name: "Set up environment for OpenBao"
  hosts: openbao
  gather_facts: true

  vars_files:
    - vars.yaml

  vars:
    opnsense_tls_directory: "/homelab/openbao/tls/opnsense"
    openbao_version: "2.4.1"

  tasks:
    - name: Install packages needed for OpenBao
      become: true
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - xz-utils # Needed for unpacking the .deb package
          - jq

    - name: Check if OpenBao binary exists
      ansible.builtin.stat:
        path: "/usr/bin/bao"
      register: openbao_binary

    - name: Retrieve OpenBao binary version
      ansible.builtin.command: "bao version | grep 'OpenBao' | head -n 1 | awk '{print $2}'"
      changed_when: false
      when: openbao_binary.stat.exists
      register: current_openbao_version

    - name: Install OpenBao
      become: true
      ansible.builtin.apt:
        deb: "https://github.com/openbao/openbao/releases/download/v{{ vars.openbao_version }}/bao_{{ vars.openbao_version }}_linux_amd64.deb"
      when: not openbao_binary.stat.exists or current_openbao_version.stdout != "v" ~ vars.openbao_version

    # TODO: Automate the version upgrade by restarting each machine in the
    # cluster starting with the standby nodes and then the active.

    - name: Create data directory
      become: true
      ansible.builtin.file:
        path: "/homelab/storage/openbao/data/"
        state: directory
        owner: openbao
        group: openbao
        mode: "0755"

    - name: Create config directory
      become: true
      ansible.builtin.file:
        path: "/etc/openbao/"
        state: directory
        mode: "0755"

    - name: Set authorized key for OPNSense to upload TLS certificate
      become: true
      ansible.posix.authorized_key:
        user: admin
        state: present
        key: "{{ lookup('file', '../../configs/opnsense_authorized_key.pub') }}"

    - name: Create TLS directory for OpenBao
      become: true
      ansible.builtin.file:
        path: "{{ vars.openbao_tls_directory }}"
        state: directory
        owner: openbao
        group: admin
        mode: "0775"

    - name: Create TLS directory for OPNSense certificates
      become: true
      ansible.builtin.file:
        path: "{{ vars.opnsense_tls_directory }}"
        state: directory
        owner: admin
        group: openbao
        mode: "02750" # New files created in this directory will have group set

    - name: Set cert_type based on group membership
      ansible.builtin.set_fact:
        cert_type: "{{ 'operator.' if 'operators' in group_names else '' }}"

    - name: Lookup the certificate file
      become: true
      ansible.builtin.stat:
        path: "{{ vars.opnsense_tls_directory }}/{{ cert_type }}openbao.internal.jackie.gg/fullchain.pem"
      register: certificate_file_status

    - name: Lookup the certificate key
      become: true
      ansible.builtin.stat:
        path: "{{ vars.opnsense_tls_directory }}/{{ cert_type }}openbao.internal.jackie.gg/key.pem"
      register: certificate_key_status

    - name: Wait for the TLS certificate to exist
      ansible.builtin.wait_for:
        path: "{{ vars.opnsense_tls_directory }}/{{ cert_type }}openbao.internal.jackie.gg/fullchain.pem"
        state: present
        timeout: 300 # Maximum number of seconds to wait
      when: not certificate_file_status.stat.exists

    - name: Wait for the TLS certificate key to exist
      ansible.builtin.wait_for:
        path: "{{ vars.opnsense_tls_directory }}/{{ cert_type }}openbao.internal.jackie.gg/key.pem"
        state: present
        timeout: 300 # Maximum number of seconds to wait
      when: not certificate_key_status.stat.exists
