---
- name: "Set up environment for OpenBao"
  hosts: openbao
  gather_facts: true

  vars_files:
    - vars.yaml
  vars:
    type: "{{'operator' if 'operators' in group_names else 'cluster' }}"

  tasks:
    - name: Install packages needed for OpenBao
      become: true
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - xz-utils # Needed for unpacking the .deb package
          - jq

    - name: Check if OpenBao binary exists
      ansible.builtin.stat:
        path: "/usr/bin/bao"
      register: openbao_binary

    - name: Install OpenBao if not installed
      become: true
      ansible.builtin.apt:
        deb: "https://github.com/openbao/openbao/releases/download/v2.3.1/bao_2.3.1_linux_amd64.deb"
      when: not openbao_binary.stat.exists

    - name: Create data directory
      become: true
      ansible.builtin.file:
        path: "/homelab/storage/openbao/data/"
        state: directory
        owner: openbao
        group: openbao
        mode: "0755"

    - name: Create config directory
      become: true
      ansible.builtin.file:
        path: "/etc/openbao/"
        state: directory
        mode: "0755"

    - name: Create TLS directory for certificates and keys
      become: true
      ansible.builtin.file:
        path: "/homelab/openbao/tls/"
        state: directory
        owner: openbao
        group: openbao
        mode: "0755"
