---
- name: "Initialize environment and files"
  hosts: "nodes"
  become: true
  gather_facts: true

  vars_files:
    - vars.yaml

  tasks:
    - name: Copy authorized_keys onto the machine
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/.ssh/{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/.ssh/{{ item.dest }}"
        force: true
        mode: "0400"
      loop:
        - src: authorized_keys
          dest: authorized_keys

    - name: Copy dotfiles
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/github/dotfiles/{{ item }}"
        dest: "{{ ansible_env.HOME }}/"
        mode: "0644"
      loop:
        - .bashrc
        - .inputrc
        - .vimrc
        - .tmux.conf

    - name: Create Ansible virtual environment
      ansible.builtin.pip:
        name: "{{ packages }}"
        virtualenv: "{{ venv_dir }}/ansible"
        virtualenv_command: "python3.11 -m venv"
      vars:
        packages:
          - ansible
