---
- hosts: "nodes"
  become: yes
  gather_facts: yes

  vars_files:
    - vars.yaml

  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - vim
          - python3.11
          - python3.11-venv
          - curl
          - gnupg-agent
          - software-properties-common
          - tmux
          - sudo
          - corosync-qdevice
          # TODO: Uncomment when it's figured out how to not install for Pi
          # - libguestfs-tools # necessary for virt-customize

    - name: Add Tailscale apt repository
      deb822_repository:
        name: tailscale
        types: [deb]
        uris: "https://pkgs.tailscale.com/stable/debian"
        signed_by: "https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg"
        suites: [bookworm]
        components:
          - main
        state: present
        enabled: yes

    - name: Install Tailscale and networkd-dispatcher
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - tailscale
          - networkd-dispatcher

