---
- name: "Apply laptop-specific settings"
  hosts: "laptops"
  become: true
  gather_facts: true

  vars_files:
    - vars.yaml

  tasks:
    - name: Prevent shutdown on lid close
      ansible.builtin.lineinfile:
        dest: /etc/systemd/logind.conf
        regexp: "^#{{ item.key }}=.*$"
        line: "{{ item.key }}={{ item.value }}"
      loop:
        - key: HandleLidSwitch
          value: ignore
        - key: HandleLidSwitchExternalPower
          value: ignore
        - key: HandleLidSwitchDocked
          value: ignore

    - name: Restart system-logind.service
      ansible.builtin.service:
        name: systemd-logind
        state: restarted
