---
openbao:
  children:
    nodes:
    operators:
nodes:
  hosts:
    node-00:
      ansible_host: node-00.openbao.internal.jackie.gg
    node-01:
      ansible_host: node-01.openbao.internal.jackie.gg
    node-02:
      ansible_host: node-02.openbao.internal.jackie.gg

operators:
  hosts:
    operator-00:
      ansible_host: operator-00.openbao.internal.jackie.gg
