control_plane:
  hosts:
    control1:
      ansible_host: 10.0.11.0
      internal_ip: 172.0.11.0

worker_nodes:
  hosts:
    worker1:
      ansible_host: 10.0.11.10
      internal_ip: 172.0.11.10
    worker2:
      ansible_host: 10.0.11.11
      internal_ip: 172.0.11.11
    worker3:
      ansible_host: 10.0.11.7
      internal_ip: 172.0.11.7

