---
- hosts: control1
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Initialize the Kubernetes cluster
      command: "kubeadm init --pod-network-cidr {{ pod_cidr }}"
      args:
        creates: /etc/kubernetes/admin.conf
      register: kube_init

    - name: Show kube_init info
      debug:
        var: kube_init

    - name: Create .kube directory in user home
      become: yes
      become_user: "{{ kubernetes_user }}"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin configuration to user .kube directory
      copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ kubernetes_user }}/.kube/config"
        owner: "{{ kubernetes_user }}"

    - name: Apply Calico networking
      become: yes
      become_user: "{{ kubernetes_user }}"
      command: "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/calico.yaml"

    - name: Get the token for worker nodes
      become: yes
      become_user: "{{ kubernetes_user }}"
      command: kubeadm token create --print-join-command
      register: kubernetes_join

    - name: Join command
      debug:
        var: kubernetes_join

    - name: Move command to local file in /tmp/
      become: yes
      local_action: copy content="{{ kubernetes_join.stdout_lines[0] }}" dest="{{ join_location }}"
