---
- name: Create virtual environment
  import_playbook: ../utilities/venv.yaml

- name: Install Helm
  import_playbook: ../utilities/helm.yaml

- name: Initialize cert-manager
  import_playbook: cert-manager.yaml
