---
- name: "Install packages for Technitium"
  hosts: technitium
  gather_facts: true

  vars_files:
    - vars.yaml

  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - qemu-guest-agent
          - dnsutils
          - mariadb-server

    - name: Start QEMU Guest Agent
      become: true
      ansible.builtin.service:
        name: qemu-guest-agent
        state: "started"
        enabled: true
