---
- name: "Install packages for Technitium"
  hosts: technitium
  gather_facts: true

  vars_files:
    - vars.yaml

  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - dnsutils
          - mariadb-server
          # - default-mysql-client
          - python{{ python_version }}
          - python{{ python_version }}-venv
          - python3-packaging

    - name: Create virtual environment
      ansible.builtin.command:
        cmd: "python{{ python_version }} -m venv {{ venv_path }}"
        creates: "{{ venv_path }}/bin/activate"

    - name: Install packages into the virtual environment
      ansible.builtin.pip:
        name: "{{ packages }}"
        virtualenv: "{{ venv_path }}"
        state: present
      vars:
        packages:
          - "PyMySQL=={{ pymysql_version }}"
