---
- name: "Install Technitium"
  hosts: technitium
  gather_facts: true

  vars_files:
    - vars.yaml

  tasks:
    - name: Download Technitium install script
      ansible.builtin.get_url:
        url: https://download.technitium.com/dns/install.sh
        dest: /tmp/technitium-install.sh
        mode: "0755"

    - name: Install Technitium via the shell script.
      become: true
      ansible.builtin.command: /tmp/technitium-install.sh
      # The script itself checks when Technitium is installed so should be safe
      # to run every time.
      changed_when: true
